### PR TITLE
Change global @variables to parameters and export all methods

### PR DESCRIPTION
**Pull request by amire80**

### CODE REVIEW

**Comment by zeljkofilipin** [comment]
:+1: 
@vikassy, @marxarelli, what do you think?

**Comment by marxarelli** [comment]
The decision of whether to use module methods over instance methods really depends on how you intend this gem to be used. If it's meant to be used in the context of Cucumber, then I would implement instance methods and mixin the module to the `World` object. It's just more congruent with other Cucumber libraries, including our own.

On the other hand, if you intend for it to be useful outside of Cucumber (with just a dependency on watir) the the module methods that require `browser` as an argument are probably fine.

**Comment by vikassy** [comment]
Thank you @marxarelli for commenting
I don't think we ever plan to use this outside cucumber, what do you think? @amire80 @zeljkofilipin

**Comment by zeljkofilipin** [comment]
This could be a generic library, there is no need to depend on Cucumber.

**Pull request merged**
